language: go
os: "linux"
sudo: false

go:
  - 1.9.x
  - 1.10.x
  - 1.15.x

notifications:
  email: false

install:
  - go get github.com/bbdshow/gocache
script:
  - pushd $TRAVIS_BUILD_DIR
  - ./test.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)  